# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and build

on: #Cuando se tiene que ejecutar el workflow
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: #Pueda leer el contenido del repositorio
  contents: read
  contents: write

jobs:
  test_and_build:

    runs-on: ubuntu-latest #El entorno donde se va a ejecutar el workflow

    steps:
    - uses: actions/checkout@v4 #Clona el repositorio
    - name: Set up Python 3.10 #Configura la version de python
      uses: actions/setup-python@v3 
      with:
        python-version: "3.10" #Version de python a usar
    - name: Install dependencies
      run: pip install -r requirements.txt #Instala las dependencias del proyecto
    - name: Check listing
      working-directory: src #Directorio donde se encuentran las pruebas
      run: ruff check . #Ejecuta el linter ruff
    - name: Test with pytest
      working-directory: src #Directorio donde se encuentran las pruebas
      run: pytest tests.py #Ejecuta las pruebas con pytest
    - name: Login to GitHub Container Registry #Inicia sesion en el registro de contenedores de GitHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/anunezb18/EjemploGithubActions:latest
    
    