# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and build

on: #Cuando se tiene que ejecutar el workflow
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: #Pueda leer el contenido del repositorio
  contents: read

jobs:
  test_and_build:

    runs-on: ubuntu-latest #El entorno donde se va a ejecutar el workflow

    steps:
    - uses: actions/checkout@v4 #Clona el repositorio
    - name: Set up Python 3.10 #Configura la version de python
      uses: actions/setup-python@v3 
      with:
        python-version: "3.10" #Version de python a usar
    - name: Install dependencies
      run: pip install -r requirements.txt #Instala las dependencias del proyecto
    - name: Test with pytest
      working-directory: src #Directorio donde se encuentran las pruebas
      run: pytest tests.py #Ejecuta las pruebas con pytest